<%@ Page Title="" Language="C#" MasterPageFile="~/Demomaster.Master" AutoEventWireup="true" CodeBehind="DataGridMultiple.aspx.cs" Inherits="DemoWebApplication2.DataGridMultiple" %>
<%@ Register assembly="AjaxControlToolkit" namespace="AjaxControlToolkit" tagprefix="ajaxToolkit" %>
<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
    <table border="1"><tr><td>Student Details</td><td>
        <asp:GridView ID="GrdSudents" runat="server" AutoGenerateColumns="true" AllowPaging="true" OnRowDataBound="GrdSudents_RowDataBound" OnSelectedIndexChanged="GrdSudents_SelectedIndexChanged" ></asp:GridView>
    </td></tr>
        <tr><td>Course Details</td><td> <asp:GridView ID="GrdPhotoDetails" runat="server" AutoGenerateColumns="true" AllowPaging="true"  PageSize="2" AutoGenerateDeleteButton="true" AutoGenerateEditButton="true" AutoGenerateSelectButton="true"></asp:GridView></td></tr>
        <tr><td></td><td>


            <%--<asp:GridView ID="GridView1" runat="server" AllowPaging="True" AllowSorting="True" AutoGenerateColumns="False" DataKeyNames="sno" DataSourceID="SqlDataSource1" PageSize="3">
                <Columns>
                    
                    <asp:CommandField ShowSelectButton="True" />
                    <asp:BoundField DataField="sno" HeaderText="sno" InsertVisible="False" ReadOnly="True" SortExpression="sno" />
                    <asp:BoundField DataField="sname" HeaderText="sname" SortExpression="sname" />
                    <asp:BoundField DataField="course" HeaderText="course" SortExpression="course" />
                    <asp:BoundField DataField="fee" HeaderText="fee" SortExpression="fee" />
                    <asp:BoundField DataField="photo1" HeaderText="photo1" SortExpression="photo1" />
                </Columns>
            </asp:GridView>
            <asp:SqlDataSource ID="SqlDataSource1" runat="server" ConnectionString="<%$ ConnectionStrings:PartitionTestConnectionString %>" SelectCommand="SELECT [sno], [sname], [course], [fee], [photo1] FROM [student] ORDER BY [sname]"></asp:SqlDataSource>--%>




                     </td></tr>


    </table>
</asp:Content>
