<%@ Page Language="C#"  MasterPageFile="~/Demomaster.Master" AutoEventWireup="true" CodeBehind="DataGridDisconnect.aspx.cs" Inherits="DemoWebApplication2.DataGridDemo1" %>


<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
    <style>
        div.sticky {
            /*position: -webkit-sticky;*/
            position: sticky;
            top: 0;
            padding: 5px;
            background-color: #cae8ca;
            border: 2px solid #4CAF50;
        }
        div{
            text-align:justify;
            text-align-last:end;
            
        }
        p{
            /*text-decoration:dashed;
            text-decoration-color:aqua;*/
            /*text-shadow: 2px 1px #ff0000;*/
            text-transform:uppercase;
        }
    </style>

</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
    <div class="row">
        <div class="col-xs-12">
             <asp:Label ID="lblmsg" runat="server" Text="Label"></asp:Label>
            <div class="sticky">I am sticky!
            
                </div>
        </div>
     </div>

    <div class="row">
    <div class="col-xs-12">
       
      
                <%-- <asp:GridView ID="GridView1" runat="server" AutoGenerateColumns="False" DataSourceID="SqlDataSource1" AllowPaging="true" AllowSorting="true" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" AutoGenerateSelectButton="True" PageSize="5" ShowFooter="True" OnRowCancelingEdit="GridView1_RowCancelingEdit" OnRowDeleting="GridView1_RowDeleting" OnRowEditing="GridView1_RowEditing" OnRowUpdating="GridView1_RowUpdating" OnSelectedIndexChanged="GridView1_SelectedIndexChanged" >
                <Columns>
                    <asp:BoundField DataField="rownum" HeaderText="rownum" ReadOnly="True" SortExpression="rownum" />
                    <asp:BoundField DataField="Customer" HeaderText="Customer" SortExpression="Customer" />
                    <asp:BoundField DataField="CategorName" HeaderText="CategorName" SortExpression="CategorName" />
                    <asp:BoundField DataField="Measure" HeaderText="Measure" SortExpression="Measure" />
                    <asp:BoundField DataField="RecordDate" HeaderText="RecordDate" SortExpression="RecordDate" />
                    <asp:BoundField DataField="Outlet" HeaderText="Outlet" SortExpression="Outlet" />
                    <asp:BoundField DataField="DistictName" HeaderText="DistrictName" SortExpression="DistictName" />
                    <asp:BoundField DataField="level2" HeaderText="level2" SortExpression="level2" />
                    <asp:BoundField DataField="level3" HeaderText="level3" SortExpression="level3" />
                    <asp:BoundField DataField="ChannelName" HeaderText="ChannelName" SortExpression="ChannelName" />
                    <asp:BoundField DataField="Expr1" HeaderText="Expr1" SortExpression="Expr1" />
                    <asp:BoundField DataField="Expr2" HeaderText="Expr2" SortExpression="Expr2" />
                    <asp:BoundField DataField="CoveredBy" HeaderText="CoveredBy" SortExpression="CoveredBy" />
                    <asp:BoundField DataField="PhotoPath" HeaderText="PhotoPath" SortExpression="PhotoPath" />
                </Columns>
                </asp:GridView>
                <asp:SqlDataSource ID="SqlDataSource1" runat="server" ConnectionString="<%$ ConnectionStrings:PartitionTestConnectionString %>" 
                    SelectCommand="usp_PhotoGetData" SelectCommandType="StoredProcedure">
                    <SelectParameters>
                        <asp:Parameter DefaultValue="1" Name="pageno" Type="Int32" />
                    </SelectParameters>
                </asp:SqlDataSource>--%>

                 <asp:GridView ID="GridView1" runat="server" AutoGenerateColumns="False"  AllowSorting="True"
                      AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" AutoGenerateSelectButton="True"   
                     ShowFooter="True" OnRowCancelingEdit="GridView1_RowCancelingEdit" 
                     OnRowDeleting="GridView1_RowDeleting" OnRowEditing="GridView1_RowEditing" 
                     OnRowUpdating="GridView1_RowUpdating" OnSelectedIndexChanged="GridView1_SelectedIndexChanged" 
                     OnPageIndexChanging="GridView1_PageIndexChanging" OnSelectedIndexChanging="GridView1_SelectedIndexChanging" 
                      
                     >
                    
                <Columns>
                    
                  <asp:BoundField DataField="sno" HeaderText="sno" ReadOnly="True" SortExpression="sno" />
                    <asp:BoundField DataField="sname" HeaderText="Student name" SortExpression="sname" />
                    <asp:BoundField DataField="course" HeaderText="course" SortExpression="course" />
                    <asp:BoundField DataField="fee" HeaderText="fee" SortExpression="fee" />
                    
                    
                     <%--  <asp:TemplateField>
                         <ItemTemplate>
                            
                                <asp:Label ID="editIDLabel" runat="server" Text='<%#  Bind("sname")  %>'></asp:Label>                                   
                        
                        </ItemTemplate>

                <%--         <ItemTemplate>
                            <asp:Label ID="Label1" runat="server" Text="<% # Bind(sname)%>"></asp:Label>
                          </ItemTemplate>


                            <EditItemTemplate>
                        
                                <asp:TextBox ID="editIDTextbox" Columns="2" runat="server" Text='<%#  Bind("sname")  %>'></asp:TextBox>
                        
                        </EditItemTemplate>


                        
                    </asp:TemplateField>--%>
                </Columns>
                     
                   
                     
                </asp:GridView>
          <%--      <div id="div1">
                 <p>
            This example is a quick exercise to illustrate how the default, static navbar and
            fixed to top navbar work. It includes the responsive CSS and HTML, so it also adapts
            to your viewport and device.
        </p>
                    </div>
          <p>
            This example is a quick exercise to illustrate how the default, static navbar and
            fixed to top navbar work. It includes the responsive CSS and HTML, so it also adapts
            to your viewport and device.
        </p>
          <p>
            This example is a quick exercise to illustrate how the default, static navbar and
            fixed to top navbar work. It includes the responsive CSS and HTML, so it also adapts
            to your viewport and device.
        </p>

          <p>
            This example is a quick exercise to illustrate how the default, static navbar and
            fixed to top navbar work. It includes the responsive CSS and HTML, so it also adapts
            to your viewport and device.
        </p>

          <p>
            This example is a quick exercise to illustrate how the default, static navbar and
            fixed to top navbar work. It includes the responsive CSS and HTML, so it also adapts
            to your viewport and device.
        </p>
          <p>
            This example is a quick exercise to illustrate how the default, static navbar and
            fixed to top navbar work. It includes the responsive CSS and HTML, so it also adapts
            to your viewport and device.
        </p>--%>
                
              
                  
    </div>
    </div>

     <div class="row">
        <div class="col-xs-12">
             <asp:Button ID="btnUpdate" runat="server" Text="Update DB" OnClick="btnUpdate_Click" CssClass="btn btn-default" style="text-align: center" />
                   <asp:Button ID="btnInsert" runat="server" OnClick="btnInsert_Click" CssClass="btn btn-default"  Text="Insert Row" />
        </div>
     </div>
   </asp:Content>
